### ISSUE TITLE
[FIX] - Setear credenciales para kaggle y hugging face

### ISSUE THREAD

**Issue by jmarshall94** [TPLenguajesParaDS/keras-benchmarks#7]
Siguiendo las instrucciones en el readme de keras benchmark agregar la variable de entorno a las imagenes de docker 

Probar correr alguno de los frameworks para ver que corra bien el modelo de gemma (que es el que usa kaggle) 

En el readme creo que explica como correr 1 solo modelo (asi no te comes el tiempo de espera de los primeros modelos) 
O cambia el orden de los modelos en el run.sh 

No usar keras-jax para probarlo

recomendacion: hacer load de keras-tensorflow.tar

**Comment by abibilonilombardi** [comment]
pip3 install --upgrade huggingface_hub
huggingface-cli login

export KAGGLE_USERNAME=ayelenbl && export KAGGLE_KEY="b....5"

ACPETAR https://www.kaggle.com/models/google/gemma/license/consent?kaggleLogin=true
